### ISSUE TITLE
Publish to Maven central repo

### ISSUE THREAD

**Issue by ymikhailenko** [rdehuyss/jobrunr-storage-cassandra#1]
This project looks like a snippet. Can it be published as a library or even included into official Jobrunr distribution?
Not clear how this code is licensed. If it's LGPL same as Jobrunr, I cannot even use it :)

**Comment by rdehuyss** [comment]
Sorry, did not see this issue. To be honest, I'm not a big fan of Cassandra and hence this storage provider was more of an experiment. The querying was too hard and it is not compatible with JobRunr anymore.
